### ISSUE TITLE
Multiple highlights on same line

### ISSUE THREAD

**Issue by vsopko** [mrlacey/VSHighlighter#5]
If you change the highlight color several times on one line, the color will not just change, but will blend/overlap with the previous one.
And if you select the same color several times on one line, it will also blend. Eventually, after many such changes, the code text itself will become unrecognizable. Looks like a bug.

**Comment by mrlacey** [comment]
@vsopko  Are you using v1.3 or v1.4?

With 1.4, I am unable to recreate hat you describe.

In the partial screenshot below, 
- I selected most of the line and highlighted in pink,
- then I selected a slightly smaller area and highlighted in gold,
- then a slightly smaller are and highlighted in blue
- then a slightly smaller are and highlighted in green
- then a slightly smaller are and highlighted in pink
- etc., etc.

![image](https://github.com/user-attachments/assets/d8d56f35-a9e9-46a0-ab8f-c7ae5eba6129)
 

v1.4 includes a change to increase the opacity so that it's not as much of an issue when highlights overlap.

As a further example, in the below image I created a multi-line highlight in pink and then another in green that overlaps.
As such the three lines that overlap produce a darker green highlight.

![image](https://github.com/user-attachments/assets/f9c70f12-8a56-4d2a-88c5-a4b20feb7ac4)

Even with multiple different color overlapping highlights applied, the last applied highlight is still clearly of the specified color.

![image](https://github.com/user-attachments/assets/07277c7c-59fc-44c5-b8be-14e08f1b0956)


I want there to be a partial transparency with the highlights so there's the potential to see a difference when multiple overlapping highlights are applied.

However, I also don't have a good use-case for wanting to create multiple overlapping highlights...

**Comment by vsopko** [comment]
v.1.4. Sample of multiple selecting same highlight color on same line. Yellow color become less transparent on each click.

https://github.com/user-attachments/assets/3af79d55-112a-441d-aad2-cc61c7942ecd

PS
1. It looks that on dark theme predefined backgrounds it is too bright to underlying text recognition.
2. May be it is better to make mark lines on scroll bar with slightly thinner height. It is hard to visualy split colors when there are many marks in close position.

**Comment by mrlacey** [comment]
v1.5 (just submitted to the marketplace) prevents the creation of multiple highlights at the same location. This means you will no longer see the color change if you repeatedly click on one of the colored buttons.

You will still see a slight color change if multiple overlapping highlights are created.
